/**
 * @file apps/api/src/config/env-keys.ts
 * @author Guy Romelle Magayano
 * @description Canonical environment variable keys consumed by the API gateway runtime.
 */

/** Canonical API gateway environment variable keys. */
export const API_ENV_KEYS = {
  NODE_ENV: "NODE_ENV",
  PORT: "PORT",
  API_PORT: "API_PORT",
  API_GATEWAY_CORS_ORIGINS: "API_GATEWAY_CORS_ORIGINS",
  API_GATEWAY_CONTENT_PROVIDER: "API_GATEWAY_CONTENT_PROVIDER",
  SANITY_STUDIO_PROJECT_ID: "SANITY_STUDIO_PROJECT_ID",
  SANITY_STUDIO_DATASET: "SANITY_STUDIO_DATASET",
  SANITY_API_VERSION: "SANITY_API_VERSION",
  SANITY_API_READ_TOKEN: "SANITY_API_READ_TOKEN",
  SANITY_USE_CDN: "SANITY_USE_CDN",
  SANITY_REQUEST_TIMEOUT_MS: "SANITY_REQUEST_TIMEOUT_MS",
  SANITY_REQUEST_MAX_RETRIES: "SANITY_REQUEST_MAX_RETRIES",
  SANITY_REQUEST_RETRY_DELAY_MS: "SANITY_REQUEST_RETRY_DELAY_MS",
  NEXT_PUBLIC_SANITY_PROJECT_ID: "NEXT_PUBLIC_SANITY_PROJECT_ID",
  NEXT_PUBLIC_SANITY_DATASET: "NEXT_PUBLIC_SANITY_DATASET",
  NEXT_PUBLIC_SANITY_API_VERSION: "NEXT_PUBLIC_SANITY_API_VERSION",
} as const;

export type ApiEnvKey = (typeof API_ENV_KEYS)[keyof typeof API_ENV_KEYS];
